# Pages CMS configuration for roicort.github.io/dasein
# More on: https://pagescms.org/docs/configuration/

media:
  - name: assets
    label: Assets
    input: src/assets
    output: ../../assets
    # Show both images and common document types in the media browser
    categories: [image, document]

content:
  # Blog posts (Markdown / MDX files with YAML frontmatter)
  - name: blog
    label: Blog
    type: collection
    path: src/content/blog
    # files will be created with a date + title-based filename
    filename: "{year}-{month}-{day}-{primary}.md"
    format: yaml-frontmatter
    subfolders: false
    view:
      fields: [title, pubDate]
      primary: title
      sort: [pubDate, title]
      default:
        search: ""
        sort: pubDate
        order: desc
    fields:
      - name: title
        label: Title
        type: string
        required: true

      - name: description
        label: Description
        type: text

      - name: pubDate
        label: Publish date
        type: date
        required: true

      - name: updatedDate
        label: Updated date
        type: date

      - name: heroImage
        label: Hero image
        type: image

      # 'body' is reserved and will map to the Markdown content (frontmatter + body)
      - name: body
        label: Content
        type: rich-text

  # Projects
  - name: projects
    label: Projects
    type: collection
    path: src/content/projects
    # files will be created with a date + title-based filename
    filename: "{primary}.md"
    format: yaml-frontmatter
    subfolders: false
    view:
      fields: [title, pubDate]
      primary: title
      sort: [pubDate, title]
      default:
        search: ""
        sort: pubDate
        order: desc
    fields:
      - name: title
        label: Title
        type: string
        required: true

      - name: description
        label: Description
        type: text

      - name: pubDate
        label: Publish date
        type: date
        required: true

      - name: updatedDate
        label: Updated date
        type: date

      - name: heroImage
        label: Hero image
        type: image

      # 'body' is reserved and will map to the Markdown content (frontmatter + body)
      - name: body
        label: Content
        type: rich-text

  # Artworks
  - name: Artworks
    label: Art
    type: collection
    path: src/content/artworks
    # files will be created with a date + title-based filename
    filename: "{primary}.md"
    format: yaml-frontmatter
    subfolders: false
    view:
      fields: [title, pubDate]
      primary: title
      sort: [pubDate, title]
      default:
        search: ""
        sort: pubDate
        order: desc
    fields:
      - name: title
        label: Title
        type: string
        required: true

      - name: description
        label: Description
        type: text

      - name: pubDate
        label: Publish date
        type: date
        required: true

      - name: updatedDate
        label: Updated date
        type: date

      - name: heroImage
        label: Hero image
        type: image

      # 'body' is reserved and will map to the Markdown content (frontmatter + body)
      - name: body
        label: Content
        type: rich-text

  # Sections is a YAML file containing a list of section objects.
  - name: CV
    label: CV
    type: file
    path: src/content/cv.yml

  - name: site
    label: Configuration
    path: src/site-config.yml
    type: file

settings:
  # When saving, merge submitted fields with existing file content instead of overwriting
  content:
    merge: true
